PersonalWebsite/Models/LearningExperience.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PersonalWebsite.Models
{
    public class LearningExperience
    {
        [Key]
        public int Id { get; set; }
        public string School { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public string Major { get; set; }
        public string Degree { get; set; }
    }
}

PersonalWebsite/Models/PersonalDbContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace PersonalWebsite.Models
{
    public class PersonalDbContext : DbContext
    {
        public PersonalDbContext() : base("name=CodeFirstDbContext")
        {

        }
        public DbSet<PersonalInformation> infos { set; get; }
        public DbSet<WorkingExperience> work { get; set; }
        public DbSet<LearningExperience> school { get; set; }
        public DbSet<Photo> Photos { get; set; }
    }
}

PersonalWebsite/Models/PersonalInformation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace PersonalWebsite.Models
{
    public class PersonalInformation
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public bool Marriage { get; set; }
        [Required]
        [StringLength(11)]
        public string Tel { get; set; }
        public string ResidentialAddress  { get; set; }
        public string NativePlace { get; set; }
        public string Email { get; set; }
        public string QQ { get; set; }
        public string Wechat { get; set; }


    }
}

PersonalWebsite/Models/Photo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PersonalWebsite.Models
{
    public class Photo
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(20)]
        public string ImageUrl { get; set; }
        public string Location { get; set; }
        public string Title { get; set; }
    }
}

PersonalWebsite/Models/WorkingExperience.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PersonalWebsite.Models
{
    public class WorkingExperience
    {
        [Key]
        public int Id { get; set; }
        public string WorkingCompany { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public string Position { get; set; }
        public string Task { get; set; }
        public int WorkingLife { get; set; }
    }
}

PersonalWebsite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PersonalWebsite.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult PhotoWall()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PersonalWebsite/Controllers/PersonalInformationController.cs
using PersonalWebsite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PersonalWebsite.Controllers
{
    public class PersonalInformationController : Controller
    {
        PersonalDbContext db = new PersonalDbContext();
        // GET: PersonalInformation
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult GetAllInfos()
        {
            List<PersonalInformation> infos = db.infos.ToList();
            return Json(infos,JsonRequestBehavior.AllowGet);
        }

       
        // GET: PersonalInformation/Edit/5
        //public ActionResult Edit(int id)
        //{
            
        //    PersonalInformation info = db.infos.Where(p => p.Id == id).FirstOrDefault();
        //    if(info!=null) return View(info);
        //    else
        //    {
        //        return   View();
        //    }
        //}

        // POST: PersonalInformation/Edit/5
        [HttpPost]
        public ActionResult Edit(PersonalInformation info)
        {
            try
            {
                var result = db.infos.Find(info.Id);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [HttpPost]
        public ActionResult Create(PersonalInformation info)
        {
            try
            {
                db.infos.Add(info);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }
    }
}

PersonalWebsite/Controllers/PhotoController.cs
using PersonalWebsite.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
using PersonalWebsite.Common;
using PersonalWebsite.DAL;
using System.Diagnostics;

namespace PersonalWebsite.Controllers
{
    public class PhotoController : Controller
    {
        PersonalDbContext db = new PersonalDbContext();
        
        // GET: Photo
        public ActionResult Index()

        {
            //Photo photo = new Photo { ImageUrl = "imag1.jpg" };
            //var pas = SqlHelper.GetSqlParameters(photo);
            string s = "select Id,ImageUrl from photos ";
            IDataReader sdr = DbFactory.ExcuteReader(CommandType.Text, s);
            List<Photo> photos = sdr.ToList<Photo>();
            return View();
        }
        public JsonResult GetAllInfos()
        {
            List<Photo> infos = db.Photos.ToList();
            return Json(infos, JsonRequestBehavior.AllowGet);
        }
        // GET: Photo/Edit/5
        public ActionResult Edit(int id)
        {

            if(id==0)
            {
                return View(new Photo());
            }
            else
            {
                var photo = db.Photos.Where(p=>p.Id==id).FirstOrDefault();
                return View(photo);
            }
         
        }

        // POST: Photo/Edit/5
        [HttpPost]
        public ActionResult Edit(Photo photo)
        {
            try
            {
                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase file = Request.Files[0];
                    string path = Server.MapPath("~/Uploading/Img/");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }
                    string fileName = file.FileName;
                    string filePath = path + fileName;
                    photo.ImageUrl = filePath;
                    file.SaveAs(filePath);
                }

                // TODO: Add update logic here
                if (photo.Id==0)
                {
                    db.Photos.Add(photo);
                 
                }
                else
                {
                    var result = db.Photos.Where(p => p.Id == photo.Id).FirstOrDefault();
                    result = photo;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Photo/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Photo/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PersonalWebsite/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<div id="app">
    <div class="container">
        <div>

        </div>
        <div class="row">
            <div class="col-md-2">
                <span class="">姓名</span>
            </div>
            <div class="col-md-10">
                <span>康良红</span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <span>年龄</span>
            </div>
            <div class="col-md-10">
                <span>26</span>
            </div>
        </div>
    </div>
  
</div>

PersonalWebsite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <h2>关于我</h2>
            <h5>我的照片：</h5>
            <div class="fakeimg">
               <img src="~/Images/klh.jpg" alt="自拍照" style="width:300px;height:250px;" />
            </div>
            <p>一个web工程师，摄影爱好者，喜欢音乐，喜欢旅行，喜欢大自然，热爱生活</p>
            <h3>技术博客链接</h3>
            <p>描述文本</p>
            <ul class="nav nav-pills nav-stacked">
                <li class="active"><a href="https://www.cnblogs.com/xiaoxinstart/p/14022951.html">sql注入与参数化查询</a></li>
                <li><a href="https://www.cnblogs.com/xiaoxinstart/p/13963836.html">接口和抽象类的区别 </a></li>
                <li><a href="https://www.cnblogs.com/xiaoxinstart/p/12862738.html">c# 对于委托，事件，泛型的理解 </a></li>
            </ul>
            <hr class="hidden-sm hidden-md hidden-lg" />
        </div>
        <div class="col-lg-8">
            <h2>标题</h2>
            <h5>副标题</h5>
            <div class="fakeimg">图像</div>
            <p>一些文本</p>
            <p>菜鸟教程，学的不仅是技术，更是梦想！！！菜鸟教程，学的不仅是技术，更是梦想！！！菜鸟教程，学的不仅是技术，更是梦想！！！</p>
            <br>
            <h2>标题</h2>
            <h5>副标题</h5>
            <div class="fakeimg">图像</div>
            <p>一些文本</p>
            <p>菜鸟教程，学的不仅是技术，更是梦想！！！菜鸟教程，学的不仅是技术，更是梦想！！！菜鸟教程，学的不仅是技术，更是梦想！！！</p>
        </div>
    </div>
</div>

PersonalWebsite/Views/Home/PhotoWall.cshtml
@{
    ViewBag.Title = "PhotoWall";
}

PersonalWebsite/Views/PersonalInformation/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

PersonalWebsite/Views/PersonalInformation/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<style type="text/css">

    .container {
    margin:0;
    }
</style>

<div id="app" class="container">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>序号</th>
                <th>姓名</th>
                <th>年龄</th>
                <th>性别</th>
                <th>婚否</th>
                <th>电话号码</th>
                <th>居住地址</th>
                <th>籍贯</th>
                <th>电子邮件</th>
                <th>QQ</th>
                <th>微信号</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            <tr v-for="(item,index) in infos">
                <td><input type="text" v-model="item.Id" style="width:20px" /></td>
                <td> <input type="text" v-model="item.Name"  style="width:70px" /></td>
                <td> <input type="text" v-model="item.Age" style="width:30px" /></td>
                <td> <input type="text" v-model="item.Gender" /></td>
                <td> <input type="text" v-model="item.Marriage" /></td>
                <td> <input type="text" v-model="item.Tel" /></td>
                <td><input type="text" v-model="item.ResidentialAddress" /></td>
                <td><input type="text" v-model="item.NativePlace" /></td>
                <td><input type="text" v-model="item.Email" /></td>
                <td><input type="text" v-model="item.QQ" /></td>
                <td><input type="text" v-model="item.Wechat" /></td>
                <td>
                    <div v-if="item.Id != ''">
                        <a href="#" class="btn btn-success" v-on:click="updateInfo()">修改</a>
                    </div>
                    <div v-else>
                        <a href="#" class="btn btn-primary" v-on:click="addInfo(item)">新增</a>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>

</div>
@section scripts{
    <script>
        var app = new Vue({
            el: "#app",
            data: {
                infos: []
            },
            mounted() {
                this.getAllInfos();
            },
            methods: {
                getAllInfos: function () {
                    axios.get('@Url.Action("GetAllInfos", "PersonalInformation")')
                        .then(res => {
                            this.infos = [];
                            for (var i = 0; i < res.data.length; i++) {
                                this.infos.push(res.data[i]);
                            }
                            this.infos.push({
                                Id:0, Name: "", Age: 0, Gender: "", Tel: "", Marriage: false, ResidentialAddress: "",
                                NativePlace: "", Email: "", QQ: "", Wechat: ""
                            });});
                },
                addInfo: function (item) {
                    var url = '@Url.Action("Create", "PersonalInformation")';
                    axios.post(url, item)
                        .then(response => { alert("保存成功！"); })
                        .catch(error => { alert("保存失败") });
                },
                updateInfo: function (contact) {
                    var url = '@Url.Action("Edit", "PersonalInformation")';
                    axios.post(url, contact)
                        .then(response => { alert("保存成功！"); })
                        .catch(error => { alert("保存失败") });
                }
            }
        })
    </script>
}

PersonalWebsite/Views/Photo/Edit.cshtml
@using PersonalWebsite.Models
@model Photo

@using (Html.BeginForm("Edit", "Photo", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    <div class="form-group">
        <label for="location" class="col-md-2 control-label">拍摄地点</label>
        <div class="col-md-10">
            <input type="text" class="form-control" id="location" placeholder="请输入拍摄地点" name="location" value="@Model.Location" />
        </div>
    </div>
    <div class="form-group">
        <label for="imageUrl" class="col-md-2 control-label">上传路径</label>
        <div class="col-md-10">
            <input type="file" id="imageUrl" name="imageUrl" value="@Model.ImageUrl" />
        </div>
    </div>
    <div class="form-group">
        <label for="title" class="col-md-2 control-label">标题</label>
        <div class="col-md-10">
            <input type="text" class="form-control" id="title" name="title" value="@Model.Title" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-2">
            
        </div>
        <div class="col-md-10">
            <input type="submit" class="btn btn-success " value="保存" style="text-align:center;float:left;" />
        </div>
    </div>
    
}

PersonalWebsite/Views/Photo/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@using PersonalWebsite.Models;
@model IEnumerable<Photo>


<div id="app" class="container">
    <input type="button" class="btn btn-success"  value="Create"  v-on:click="addInfo()"/>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>序号</th>
                <th>拍摄地点</th>
                <th>上传路径</th>
                <th>标题</th>
               
            </tr>
        </thead>
        <tbody>
            <tr v-for="(item,index) in photos">
                <td>  {{item.Id}}</td>
                <td>  {{item.Location}} </td>
                <td>  {{item.ImageUrl}}</td>
                <td>  {{item.Title}} </td>
                <td>
                    <a href="#" class="btn btn-success" v-on:click="updateInfo(item.Id)">修改</a>
                </td>
            </tr>
        </tbody>
    </table>

</div>
@section scripts{
    <script>
        var app = new Vue({
            el: "#app",
            data: {
                photos: []
            },
            mounted() {
                this.getAllInfos();
            },
            methods: {
                getAllInfos: function () {
                    axios.get('@Url.Action("GetAllInfos", "Photo")')
                        .then(res => {
                            this.infos = [];
                            console.log(res.data);
                            for (var i = 0; i < res.data.length; i++) {
                                this.photos.push(res.data[i]);
                            }
                        });
                },
                addInfo: function (item) {
                    var url = '@Url.Action("Edit", "Photo",new { id=0})';
                    window.location.href = url;
                 
                },
                updateInfo: function () {
                    var id = $（）
                   var url = '@Url.Action("Edit", "Photo",new {id= key })';
                    window.location.href = url;
                }
            }
        })
    </script>
}

PersonalWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Kong的网上花园</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="jumbotron text-center" style="margin-bottom:0">
        <h1>欢迎来到Kong's Website</h1>
        <p>我们的梦想是星辰大海</p>
    </div>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Kong'Website</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a href='@Url.Action("Index","Home")'>主页</a></li>
                    <li><a href='@Url.Action("About","Home")'>关于我</a></li>
                    <li><a href="@Url.Action("PhotoWall","Home")">照片墙</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <div class="jumbotron text-center" style="position:fixed;left:0px;bottom:0px;width:100%;height:50px;z-index:9999">
        <p>底部内容</p>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/vue");
    @RenderSection("scripts", required: false)
</body>
</html>